services:
  - type: worker
    name: agent-backend
    env: python
    plan: free
    buildCommand: |
      uv sync
      # ensure the heavy turn-detector plugin is not present so it cannot be auto-preloaded
      pip uninstall -y livekit-plugins-turn-detector || true
    startCommand: uv run python src/agent.py start
    envVars:
      - key: LIVEKIT_URL
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: CARTESIA_API_KEY
        sync: false
